=== magefree/mage/Mage.Server/src/main/java/mage/server/util/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="server"/>
				<xs:element ref="playerTypes"/>
				<xs:element ref="gameTypes"/>
				<xs:element ref="draftTypes"/>
				<xs:element ref="deckTypes"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="server">
		<xs:complexType>
			<xs:attribute name="serverAddress" type="xs:string" use="required"/>
			<xs:attribute name="serverName" type="xs:string" use="required"/>
			<xs:attribute name="port" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="secondaryBindPort" type="xs:integer" use="required"/>
      <xs:attribute name="backlogSize" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="numAcceptThreads" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="maxPoolSize" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="leasePeriod" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="maxGameThreads" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="maxSecondsIdle" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="minUserNameLength" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="maxUserNameLength" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="userNamePattern" type="xs:string" use="required"/>
      <xs:attribute name="maxAiOpponents" type="xs:string" use="optional"/>
      <xs:attribute name="saveGameActivated" type="xs:boolean" use="optional"/>
			<xs:attribute name="signingKey" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="plugin">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="jar" type="xs:string"/>
		<xs:attribute name="className" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="gamePlugin">
		<xs:complexContent>
			<xs:extension base="plugin">
				<xs:attribute name="typeName" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="playerTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="playerType" type="plugin" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="gameTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="gameType" type="gamePlugin" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="draftTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="draftType" type="plugin" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="deckTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="deckType" type="plugin" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== magefree/mage/Mage.Tests/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Config.xsd">
    <server serverAddress="0.0.0.0" serverName="mage-server" port="17171" maxGameThreads="10" maxSecondsIdle="600"/>
    <playerTypes>
        <playerType name="Computer - mad" jar="mage-player-ai-ma.jar" className="mage.player.ai.ComputerPlayer7"/>
        <playerType name="Computer - monte carlo" jar="mage-player-aimcts.jar" className="mage.player.ai.ComputerPlayerMCTS"/>
    </playerTypes>
    <gameTypes>
        <gameType name="Two Player Duel" jar="mage-game-twoplayerduel.jar" className="mage.game.TwoPlayerMatch" typeName="mage.game.TwoPlayerDuelType"/>
    </gameTypes>
    <tournamentTypes>
        <tournamentType name="Elimination Booster Draft" jar="mage-tournament-booster-draft.jar" className="mage.tournament.BoosterDraftEliminationTournament" typeName="mage.tournament.BoosterDraftEliminationTournamentType"/>
    </tournamentTypes>
    <deckTypes>
        <deckType name="Constructed" jar="mage-deck-constructed.jar" className="mage.deck.Constructed"/>
        <deckType name="Limited" jar="mage-deck-limited.jar" className="mage.deck.Limited"/>
    </deckTypes>
</config>

=== magefree/mage/Mage.Server/src/main/java/mage/server/util/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Config.xsd">
    <server serverAddress="0.0.0.0"
            serverName="mage-server"
            port="17171"
            secondaryBindPort="-1"
            backlogSize="200"
            numAcceptThreads="2"
            maxPoolSize="300"
            leasePeriod="5000"
            socketWriteTimeout="10000"
            maxGameThreads="10"
            maxSecondsIdle="600"
            minUserNameLength="3"
            maxUserNameLength="14"
            userNamePattern="[^a-z0-9_]"
            maxAiOpponents="15"
            saveGameActivated="false"
            authenticationActivated="false"
            googleAccount=""
            useSSL="true"
    />
    <playerTypes>
        <playerType name="Human" jar="Mage.Player.Human.jar" className="mage.player.human.HumanPlayer"/>
        <playerType name="Computer - default" jar="Mage.Player.AI.jar" className="mage.player.ai.ComputerPlayer"/>
    </playerTypes>
    <gameTypes>
        <gameType name="Two Player Duel" jar="Mage.Game.TwoPlayerDuel.jar" className="mage.game.TwoPlayerDuel" typeName="mage.game.TwoPlayerDuelType"/>
    </gameTypes>
    <deckTypes>
        <deckType name="Constructed" jar="Mage.Deck.Constructed.jar" className="mage.deck.Constructed"/>
    </deckTypes>
</config>
