=== magefree/mage/Mage.Server/src/main/xml-resources/jaxb/Config/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="server"/>
                <xs:element ref="playerTypes"/>
                <xs:element ref="gameTypes"/>
                <xs:element ref="tournamentTypes"/>
                <xs:element ref="draftCubes"/>
                <xs:element ref="deckTypes"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="server">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="home" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="internal" type="xs:string" use="required"/>
                        <xs:attribute name="external" type="xs:string" use="required" />
                        <xs:attribute name="port" type="xs:positiveInteger" use="required" />
                        <xs:attribute name="externalport" type="xs:positiveInteger" />
                        <xs:attribute name="secondaryport" type="xs:integer" default="-1" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="multihome" type="xs:boolean" default="false" />
            <xs:attribute name="serverAddress" type="xs:string" use="required"/>
            <xs:attribute name="serverName" type="xs:string" use="required"/>
            <xs:attribute name="port" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxGameThreads" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxSecondsIdle" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="secondaryBindPort" type="xs:integer" use="required"/>
            <xs:attribute name="backlogSize" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="numAcceptThreads" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxPoolSize" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="leasePeriod" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="socketWriteTimeout" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="minUserNameLength" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxUserNameLength" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="invalidUserNamePattern" type="xs:string" use="required"/>
            <xs:attribute name="minPasswordLength" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxPasswordLength" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="maxAiOpponents" type="xs:string" use="optional"/>
            <xs:attribute name="saveGameActivated" type="xs:boolean" use="optional"/>
            <xs:attribute name="authenticationActivated" type="xs:boolean" use="optional"/>
            <xs:attribute name="googleAccount" type="xs:string" use="optional"/>
            <xs:attribute name="mailgunApiKey" type="xs:string" use="optional"/>
            <xs:attribute name="mailgunDomain" type="xs:string" use="optional"/>
            <xs:attribute name="mailSmtpHost" type="xs:string" use="optional"/>
            <xs:attribute name="mailSmtpPort" type="xs:string" use="optional"/>
            <xs:attribute name="mailUser" type="xs:string" use="optional"/>
            <xs:attribute name="mailPassword" type="xs:string" use="optional"/>
            <xs:attribute name="mailFromAddress" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="plugin">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="jar" type="xs:string"/>
        <xs:attribute name="className" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="gamePlugin">
        <xs:complexContent>
            <xs:extension base="plugin">
                <xs:attribute name="typeName" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="playerTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="playerType" type="plugin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gameTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gameType" type="gamePlugin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tournamentTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tournamentType" type="gamePlugin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="draftCubes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="draftCube" type="plugin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deckTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deckType" type="plugin" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== magefree/mage/Mage.Server/release/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Config.xsd">
    <!--
    serverAddress       - ip of the XMage server. Set it to "0.0.0.0" for local host or to the IP the server should use
    port                - the port the primary server socket is bound to
    secondaryBindPort   - the port to which the secondary server socket is to be bound. if "-1" is set , an arbitrary port is selected.
    backlogSize         - the preferred number of unaccepted incoming connections allowed at a given time. The actual number may be greater
                          than the specified backlog. When the queue is full, further connection requests are rejected. The JBoss default value is 200
    numAcceptThreads    - the number of threads listening on the ServerSocket. The JBoss default value is 1
    maxPoolSize         - the maximum number of ServerThreads that can exist at any given time. The JBoss default value is 300
    leasePeriod         - To turn on server side connection failure detection of remoting clients, it is necessary to satisfy two criteria.
                          The first is that the client lease period is set and is a value greater than 0. The value is represented in milliseconds.
                          The client lease period can be set by either the 'clientLeasePeriod' attribute within the Connector configuration or by calling the Connector method
    socketWriteTimeout  - All write operations will time out if they do not complete within the configured period.
    maxGameThreads      - Number of games that can be started simultanously on the server
    maxSecondsIdle      - Number of seconds after that a game is auto conceded by the player that was idle for such a time
    minUserNameLength   - minmal allowed length of a user name to connect to the server
    maxUserNameLength   - maximal allowed length of a user name to connect to the server
    userNamePattern     - pattern for user name validity check
    maxAiOpponents      - number of allowed workable AI opponents on the server (draft bots are unlimited)
    saveGameActivated   - allow game save and replay options (not working correctly yet)
    authenticationActivated - "true" = user have to register to signon "false" = user need not to register
    * mail configs only needed if authentication is activated:
    * if mailUser = "" mailgun is used otherwise nativ mail server on the system
    googleAccount       - not supported currently
    mailgunApiKey       - key from the mailgun domain  e.g. = "key-12121111..."
    mailgunDomain       - domain for the mailgun message sending
    mailSmtpHost        - hostname to send the mail
    mailSmtpPort        - port to send the mail
    mailUser            - username used to send the mail
    mailPassword        - passworf of the used user to send the mail
    mailFromAddress     - sender address
    -->
    <server serverAddress="0.0.0.0"
            serverName="mage-server"
            port="17171"
            secondaryBindPort="-1"
            backlogSize="200"
            numAcceptThreads="2"
            maxPoolSize="300"
            leasePeriod="5000"
            socketWriteTimeout="10000"
            maxGameThreads="10"
            maxSecondsIdle="600"
            minUserNameLength="3"
            maxUserNameLength="14"
            invalidUserNamePattern="[^a-z0-9_]"
            minPasswordLength="8"
            maxPasswordLength="100"
            maxAiOpponents="15"
            saveGameActivated="false"
            authenticationActivated="false"
            googleAccount=""
            mailgunApiKey=""
            mailgunDomain=""
            mailSmtpHost=""
            mailSmtpPort=""
            mailUser=""
            mailPassword=""
            mailFromAddress=""
    />
    <playerTypes>
        <playerType name="Human" jar="mage-player-human-${project.version}.jar" className="mage.player.human.HumanPlayer"/>
        <playerType name="Computer - mad" jar="mage-player-ai-ma-${project.version}.jar" className="mage.player.ai.ComputerPlayerControllableProxy"/>
        <playerType name="Computer - draftbot" jar="mage-player-ai-draftbot-${project.version}.jar" className="mage.player.ai.ComputerDraftPlayer"/>
    </playerTypes>
    <gameTypes>
        <gameType name="Two Player Duel" jar="mage-game-twoplayerduel-${project.version}.jar" className="mage.game.TwoPlayerMatch" typeName="mage.game.TwoPlayerDuelType"/>
        <gameType name="Free For All" jar="mage-game-freeforall-${project.version}.jar" className="mage.game.FreeForAllMatch" typeName="mage.game.FreeForAllType"/>
        <gameType name="Commander Two Player Duel" jar="mage-game-commanderduel-${project.version}.jar" className="mage.game.CommanderDuelMatch" typeName="mage.game.CommanderDuelType"/>
        <gameType name="Commander Free For All" jar="mage-game-commanderfreeforall-${project.version}.jar" className="mage.game.CommanderFreeForAllMatch" typeName="mage.game.CommanderFreeForAllType"/>
        <gameType name="Tiny Leaders Two Player Duel" jar="mage-game-tinyleadersduel-${project.version}.jar" className="mage.game.TinyLeadersDuelMatch" typeName="mage.game.TinyLeadersDuelType"/>
        <gameType name="Canadian Highlander Two Player Duel" jar="mage-game-canadianhighlanderduel-${project.version}.jar" className="mage.game.CanadianHighlanderDuelMatch" typeName="mage.game.CanadianHighlanderDuelType"/>
        <gameType name="Penny Dreadful Commander Free For All" jar="mage-game-pennydreadfulcommanderfreeforall-${project.version}.jar" className="mage.game.PennyDreadfulCommanderFreeForAllMatch" typeName="mage.game.PennyDreadfulCommanderFreeForAllType"/>
        <gameType name="Pauper Commander Free For All" jar="mage-game-paupercommanderfreeforall-${project.version}.jar" className="mage.game.PauperCommanderFreeForAllMatch" typeName="mage.game.PauperCommanderFreeForAllType"/>
        <gameType name="Freeform Commander Two Player Duel" jar="mage-game-freeformcommanderduel-${project.version}.jar" className="mage.game.FreeformCommanderDuelMatch" typeName="mage.game.FreeformCommanderDuelType"/>
        <gameType name="Freeform Commander Free For All" jar="mage-game-freeformcommanderfreeforall-${project.version}.jar" className="mage.game.FreeformCommanderFreeForAllMatch" typeName="mage.game.FreeformCommanderFreeForAllType"/>
        <gameType name="Freeform Unlimited Commander" jar="mage-game-freeformunlimitedcommander-${project.version}.jar" className="mage.game.FreeformUnlimitedCommanderMatch" typeName="mage.game.FreeformUnlimitedCommanderType"/>
        <gameType name="Oathbreaker Two Player Duel" jar="mage-game-oathbreakerduel-${project.version}.jar" className="mage.game.OathbreakerDuelMatch" typeName="mage.game.OathbreakerDuelType"/>
        <gameType name="Oathbreaker Free For All" jar="mage-game-oathbreakerfreeforall-${project.version}.jar" className="mage.game.OathbreakerFreeForAllMatch" typeName="mage.game.OathbreakerFreeForAllType"/>
        <gameType name="Brawl Two Player Duel" jar="mage-game-brawlduel-${project.version}.jar" className="mage.game.BrawlDuelMatch" typeName="mage.game.BrawlDuelType"/>
        <gameType name="Brawl Free For All" jar="mage-game-brawlfreeforall-${project.version}.jar" className="mage.game.BrawlFreeForAllMatch" typeName="mage.game.BrawlFreeForAllType"/>
        <gameType name="Momir Basic Two Player Duel" jar="mage-game-momirduel-${project.version}.jar" className="mage.game.MomirDuelMatch" typeName="mage.game.MomirDuelType"/>
        <gameType name="Momir Basic Free For All" jar="mage-game-momir-${project.version}.jar" className="mage.game.MomirFreeForAllMatch" typeName="mage.game.MomirFreeForAllType"/>
    </gameTypes>
    <tournamentTypes>
        <tournamentType name="Constructed Elimination" jar="mage-tournament-constructed-${project.version}.jar" className="mage.tournament.ConstructedEliminationTournament" typeName="mage.tournament.ConstructedEliminationTournamentType"/>
        <tournamentType name="Constructed Swiss" jar="mage-tournament-constructed-${project.version}.jar" className="mage.tournament.ConstructedSwissTournament" typeName="mage.tournament.ConstructedSwissTournamentType"/>
        <tournamentType name="Booster Draft Elimination" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.BoosterDraftEliminationTournament" typeName="mage.tournament.BoosterDraftEliminationTournamentType"/>
        <tournamentType name="Booster Draft Elimination (Cube)" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.BoosterDraftEliminationTournament" typeName="mage.tournament.BoosterDraftEliminationCubeTournamentType"/>
        <tournamentType name="Booster Draft Elimination (Random)" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.RandomBoosterDraftEliminationTournament" typeName="mage.tournament.RandomBoosterDraftEliminationTournamentType"/>
        <tournamentType name="Booster Draft Elimination (Reshuffled)" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.ReshuffledBoosterDraftEliminationTournament" typeName="mage.tournament.ReshuffledBoosterDraftEliminationTournamentType"/>
        <tournamentType name="Booster Draft Elimination (Rich Man)" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.RichManDraftEliminationTournament" typeName="mage.tournament.RichManDraftEliminationTournamentType"/>
        <tournamentType name="Booster Draft Elimination (Rich Man Cube)" jar="mage-tournament-boosterdraft-${project.version}.jar" className="mage.tournament.RichManCubeDraftEliminationTournament" typeName="mage.tournament.RichManCubeDraftEliminationTournamentType"/>
